apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: email-agentpulse-backend-hpa
  namespace: email-agent
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: email-agentpulse-backend
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: email-agentpulse-frontend-hpa
  namespace: email-agent
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: email-agentpulse-frontend
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
